# Generated by Django 4.1.2 on 2022-10-15 04:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("usere", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="upload_files")),
                ("filename", models.TextField()),
                ("file_desc", models.TextField()),
                ("file_upTime", models.DateField(default=datetime.datetime.now)),
                ("file_ediTime", models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
